package ru.crazerr.cashtracker.feature.account.presentation.api.createAccountDialog

import ru.crazerr.cashtracker.core.utils.presentation.ComponentFactory

interface CreateAccountComponentFactory : ComponentFactory<CreateAccountComponent, CreateAccountComponentAction>